name: stock_keeper
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  uuid: ^4.3.2
  cupertino_icons: ^1.0.2
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  test: ^1.24.9

flutter:
  uses-material-design: true
